site_name: stoicrex
docs_dir: docs
nav:
   - Home: README.md
   - Getting Started:
      - QuickStart: quickstart.md
   - CODE:
      - particles: part.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

